version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-resume-web-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-47d29okbc9y7"
s3_prefix = "serverless-resume-web-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Env=\"dev\""
confirm_changeset = true
resolve_s3 = true
