AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless resume website backend built using SAM CLI

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ResumePutCountFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: serverless_web/resumeLambdaFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CounterTable
      Architectures:
        - x86_64
      Events:
        ResumeAPI:
          Type: Api
          Properties:
            Path: /counter
            Method: get
  CounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitorsCountTable
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

# Outputs section - makes deployment info available
# Why: Allows CI/CD to verify deployment and get API URL
Outputs:
  ApiURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  LambdaFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt ResumePutCountFunction.Arn

  DynamoDBTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref CounterTable
