name: Deploy to S3 Bucket & Invalidate CloudFront
on:
  push:
    branches:
      - main
    paths:
      - "/front-end"

jobs:
  deploy-and-invalidate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      # Upload to S3
      - name: Upload to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude '.git*/*' --delete --follow-symlinks
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_FRONT }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "front-end"
      # Invalidate Cloudfront distribution
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: "/*"
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_FRONT }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
